/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pram' at '14/05/15 15:48' with Gradle 1.12
 *
 * @author pram, @date 14/05/15 15:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
